UpdateDelegate Change UA/Collection
metaplex-foundation/mpl-core pull request #204
Opened 2024-12-16 21:34 UTC by blockiosaurus

Adding the ability to change the update authority or collection as the update delegate.

2024-12-18 03:20 UTC, danenbm requested changes

2024-12-18 03:20 UTC, danenbm commented on programs/mpl-core/src/plugins/internal/authority_managed/update_delegate.rs
> +            || self.additional_delegates.contains(ctx.authority_info.key)
I think `validate_update` is used for both asset plugins and collection plugins.  So wouldn't this allow an update delegate on an asset to remove itself from a collection, which I think we don't want per the offline discussion?

2024-12-18 03:20 UTC, danenbm commented on clients/js/test/updateV2.test.ts
> +test('it can remove an asset from collection using update delegate', async (t) => {
If my other comment is true then I think we should keep tests for not allowing asset update delegates and asset additional update delegates.

2024-12-30 19:43 UTC, nhanphan submitted a review, later dismissed

2025-02-21 18:23 UTC, blockiosaurus commented
Huge thanks to @ASCorreia for his work on #217 regarding #208.

2025-02-27 23:47 UTC, danenbm requested changes

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
Isn't this using ui as the authority for the call but should be using the update delegate?  Which I think for clarity should not be set to the owner?

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
Shouldn't the new signer be used here?

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +// Does not work with additionalDelegates
what's up with this comment it should work now?

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +// Does not work
what's up with this comment as well?

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
This is confusing as it says "as collection owner" but I don't think it is using collection authority.  Instead its using update delegate which is set to an address that just happens to be called `collectionOwner` in the test.

2025-02-27 23:47 UTC, danenbm commented on clients/js/test/updateV2.test.ts
> +test('it can remove an asset from collection as Collection authority with update delegate on asset', async (t) => {
Interesting what's the signficance of having the update delegate on asset here?

2025-02-28 00:35 UTC, blockiosaurus commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
Ah you are correct.

2025-02-28 00:35 UTC, blockiosaurus commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +// Does not work with additionalDelegates
Leftover from copy/paste, whoops.

2025-02-28 00:37 UTC, blockiosaurus commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
Yes

2025-02-28 00:38 UTC, blockiosaurus commented on clients/js/test/plugins/collection/updateDelegate.test.ts
> +  }).sendAndConfirm(umi);
Ah you're right. I think this is the name being wrong. We're making sure overlapping permissions don't break it. Even if it's a weird case.

2025-02-28 00:41 UTC, blockiosaurus commented on clients/js/test/updateV2.test.ts
> +test('it can remove an asset from collection as Collection authority with update delegate on asset', async (t) => {
We're blocking changing the collection by an asset UpdateDelegate so here I'm explicitly checking and making sure I don't break normal operations. E.g. my logic doesn't always fail if an asset has an UpdateDelegate, it only fails when the Asset UpdateDelegate is the one removing the collection.

2025-02-28 02:33 UTC, danenbm approved these changes
Approved with comment to check

2025-02-28 02:33 UTC, danenbm commented on programs/mpl-core/src/plugins/internal/authority_managed/update_delegate.rs
> +                    != &UpdateAuthority::Collection(*ctx.collection_info.unwrap().key)
// - Asset UpdateDelegates should not be able to add/remove assets from a collection


I believe this block only needs to cover "remove" which it does.
I believe "add" is covered by a code block in update.rs.

So I think we are good here.

For testing "Asset UpdateDelegates remove":
You did just add tests making sure asset update delegate cannot remove from collection, addressing the specific update delegate concern.

For testing "Asset UpdateDelegates add":
I don't think it makes sense to add a test saying asset update delegate cannot add to a collection, because it is already covered by tests such as `it cannot add asset to collection if not both asset and collection auth` which is covering the case of using an arbitrary authority that is not the collection authority.

But just wanted to request you do one last consideration of this, and resolve this comment if its covered.

2025-02-28 02:33 UTC, danenbm commented on clients/js/test/updateV2.test.ts
> +test('it can remove an asset from collection as Collection authority with update delegate on asset', async (t) => {
Yes now I remember how this relates to the asset UpdateDelegate fix

2025-02-28 20:37 UTC, blockiosaurus commented on programs/mpl-core/src/plugins/internal/authority_managed/update_delegate.rs
> +                    != &UpdateAuthority::Collection(*ctx.collection_info.unwrap().key)
Reviewed and Confirmed, thank you!

2025-02-28 20:56 UTC, merged